### PR TITLE
Devise implementation

### PR DESCRIPTION
**Pull request by gamcdonald123**
Quite a lot has been done here.

- Devise installed (you'll need to bundle install locally)
- Pages created for login, registration and editing of profile
- Avatar can be uploaded at both registration and editing. Image stored in Cloudinary
- Navbar created with logo, brand title, links and dropdown for profile

Screenshot 2024-02-27 at 16 48 13

Screenshot 2024-02-27 at 16 48 39

Screenshot 2024-02-27 at 16 48 54

### CODE REVIEW

**Review by nfarinello — APPROVED** [review]
all reviewed and ready to go :)

**Comment by antonio-propato** [comment]
🙌🏼 🙌🏼 🙌🏼 🙌🏼

**Review by Mirkica — APPROVED** [review]
Looks great! Well done!

**Review by antonio-propato — APPROVED** [review]

**Comment by soukouna94** [comment]
Great

**Pull request merged**
